<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Filespace233</RootNamespace>
    <Version>0.1.0</Version>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
    <InformationalVersion>0.1.0</InformationalVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
    <DefaultItemExcludes>$(DefaultItemExcludes);artifacts\**;AppPackages\**;BundleArtifacts\**</DefaultItemExcludes>
    <WindowsPackageType>MSIX</WindowsPackageType>
    <EnableMsixTooling>true</EnableMsixTooling>
    <WindowsAppSdkBootstrapInitialize Condition="'$(WindowsPackageType)' == 'None'">true</WindowsAppSdkBootstrapInitialize>
    <AppxPackageSigningEnabled Condition="'$(AppxPackageSigningEnabled)' == ''">false</AppxPackageSigningEnabled>
    <AppxBundle>Always</AppxBundle>
    <AppxBundlePlatforms>x64|arm64</AppxBundlePlatforms>
    <UapAppxPackageBuildMode Condition="'$(UapAppxPackageBuildMode)' == ''">StoreUpload</UapAppxPackageBuildMode>
    <GenerateAppxPackageOnBuild Condition="'$(Configuration)' == 'Store'">true</GenerateAppxPackageOnBuild>
    <AppxSymbolPackageEnabled>false</AppxSymbolPackageEnabled>
    <AppxPackageIncludePrivateSymbols>false</AppxPackageIncludePrivateSymbols>
    <AppxPackageDir>$(MSBuildProjectDirectory)\AppPackages\</AppxPackageDir>
    <UseRidGraph>true</UseRidGraph>
    <PublishAot Condition="'$(Configuration)' == 'Aot'">true</PublishAot>
    <PublishTrimmed Condition="'$(Configuration)' == 'Aot'">false</PublishTrimmed>
    <SelfContained Condition="'$(Configuration)' == 'Aot'">true</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\**\*" CopyToOutputDirectory="PreserveNewest" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.3.1" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2526" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools.WinApp" Version="0.6.0" />
  </ItemGroup>
</Project>
